name: iOS build

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check project list
        run: |
          find . -name "*.xcodeproj" -o -name "*.xcworkspace"
          xcodebuild -list

