name: iOS build

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Build project
        run: |
          echo "Vérification du projet SwiftUI..."
          xcodebuild -list

