name: iOS build

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build iOS App for Device
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Swift / Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Build for iOS Device (Archive structure)
        run: |
          swift package resolve
          xcodebuild -skipPackagePluginValidation -scheme LobikoApp -destination "generic/platform=iOS" -configuration Release archive -archivePath $PWD/build/LobikoApp.xcarchive

      - name: Upload iOS Archive Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LobikoApp-Archive
          path: build/LobikoApp.xcarchive
